// Ecommerce/sample-1-github-copilot/source/src/components/ProductCard.tsx
"use client";

import Image from "next/image";
import type { Product } from "@/lib/db/products";
import { useCart } from "@/lib/cart/context";

function formatSold(count: number): string {
  if (count >= 1000) return `Sold ${(count / 1000).toFixed(1)}k`;
  return `Sold ${count}`;
}

export default function ProductCard({ product }: { product: Product }) {
  const { addToCart } = useCart();

  return (
    <div className="product-card bg-white rounded shadow-sm overflow-hidden flex flex-col relative group cursor-pointer hover:shadow-md transition-shadow">
      <div className="aspect-square relative overflow-hidden bg-surface-container-low">
        <Image
          src={product.image_url}
          alt={product.name}
          fill
          className="object-cover"
          sizes="(max-width: 768px) 50vw, (max-width: 1200px) 25vw, 16vw"
          unoptimized
        />
        {product.discount_percent && product.discount_percent > 0 && (
          <div className="absolute top-0 right-0 bg-primary-container text-on-primary-container text-[10px] font-bold px-2 py-1">
            -{product.discount_percent}%
          </div>
        )}
        {product.is_mall && (
          <div className="absolute top-0 left-0 bg-tertiary-container text-on-tertiary-container text-[10px] font-bold px-2 py-1">
            Mall
          </div>
        )}
        {product.is_new && !product.is_mall && (
          <div className="absolute top-0 left-0 bg-secondary-container text-on-secondary-container text-[10px] font-bold px-2 py-1">
            New
          </div>
        )}
      </div>
      <div className="p-2 flex flex-col flex-1">
        <h3 className="text-xs line-clamp-2 mb-2 text-on-surface leading-snug">
          {product.name}
        </h3>
        <div className="mt-auto">
          <div className="flex items-center justify-between">
            <span className="text-primary font-bold text-base">
              ${Number(product.price).toFixed(2)}
            </span>
            <span className="text-[10px] text-outline">{formatSold(product.sold_count)}</span>
          </div>
        </div>
      </div>
      <button
        onClick={(e) => {
          e.stopPropagation();
          addToCart(product);
        }}
        className="absolute inset-x-0 bottom-0 bg-primary text-white py-2 font-bold text-xs opacity-0 group-hover:opacity-100 group-hover:translate-y-0 translate-y-full transition-all duration-200"
      >
        ADD TO CART
      </button>
    </div>
  );
}

// Ecommerce/sample-8-github-copilot-2/source/frontend/src/app/shared/components/product-card/product-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { Product } from '../../../core/models';
import { CurrencyVndPipe } from '../../pipes/currency-vnd.pipe';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [CommonModule, RouterLink, CurrencyVndPipe],
  template: `
    <div class="card group cursor-pointer hover:shadow-card-hover transition-shadow duration-300">
      <a [routerLink]="['/san-pham', product.slug]" class="block relative overflow-hidden">
        <div class="aspect-square bg-gray-100 overflow-hidden">
          <img
            [src]="product.imageUrl || 'assets/placeholder.png'"
            [alt]="product.name"
            class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            loading="lazy"
          />
        </div>

        <div class="absolute top-2 left-2 flex flex-col gap-1">
          @if (discountPercent > 0) {
            <span class="badge-sale">-{{ discountPercent }}%</span>
          }
          @if (product.isFlashSale) {
            <span class="bg-yellow-400 text-yellow-900 text-xs font-bold px-2 py-0.5 rounded">Flash Sale</span>
          }
        </div>
      </a>

      <div class="p-4">
        <a [routerLink]="['/san-pham', product.slug]">
          <p class="text-xs text-muted mb-1">{{ product.category?.name }}</p>
          <h3 class="font-semibold text-gray-900 text-sm leading-snug mb-2 line-clamp-2 hover:text-primary transition-colors">
            {{ product.name }}
          </h3>
        </a>

        <div class="flex items-center gap-2 mb-3">
          <span class="text-primary font-bold text-base">{{ product.price | currencyVnd }}</span>
          @if (product.originalPrice && product.originalPrice > product.price) {
            <span class="text-muted text-xs line-through">{{ product.originalPrice | currencyVnd }}</span>
          }
        </div>

        <button
          (click)="onAddToCart($event)"
          class="w-full btn-primary text-sm py-2"
          [disabled]="product.stock === 0"
        >
          {{ product.stock === 0 ? 'Hết hàng' : 'Thêm vào giỏ' }}
        </button>
      </div>
    </div>
  `,
})
export class ProductCardComponent {
  @Input({ required: true }) product!: Product;
  @Output() addToCart = new EventEmitter<Product>();

  get discountPercent(): number {
    if (!this.product.originalPrice || this.product.originalPrice <= this.product.price) return 0;
    return Math.round((1 - this.product.price / this.product.originalPrice) * 100);
  }

  onAddToCart(event: MouseEvent): void {
    event.preventDefault();
    this.addToCart.emit(this.product);
  }
}
